### PR TITLE
Avatar support for new version wechat

### PR DESCRIPTION
**Pull request by SwordYork**
The avatar of wechat is now cached in `/sdcard/tencent/MicroMsg/{md5id}/sfs/avatar.block.xxxxx`, and the index is located in `/data/data/com.tencent.mm/MicroMsg/{md5id}/sfs/avatar.index`.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks for your contribution!

**Comment by ppwwyyxx** [comment]
Oops I can't get your code working.
I'm testing against a contact whose 'offset' in Index_avatar table is 2818048. Then you look for avatar.block.00002, which doesn't exists for me.
I only have one avatar.block.00000 file, which is 162M.

**Comment by ppwwyyxx** [comment]
I did some tests:
Directly seeking the 'offset' in my 'avatar.block.00000' file can give me the avatar of the correct person, although with some weird color.
I'm not very clear what is going on with `start_pos = pos - 2 ** 34`.
I'm guessing that you have two avatar.block file, and the size of the first is 2**34, so you subtract it?

**Comment by ppwwyyxx** [comment]
Hi I found that the file name of the avatar (xx/xx/user_this-is-md5-of-length-32.png.bm') is stored at position `offset + 16`. Then comes a `\x00`, and the image data comes right after that.
I guess this is why your code works by searching for `\x00`.
I updated the code to calculate the offset directly without searching.

Again, I don't know about `start_pos = pos - 2 ** 34`, and I only have one avatar.block file so I don't know how to decide which block file to use. But your method to calculate the hex doesn't work for me.

Please update the code with a correct method to decide the block file and index if you can. I'm guessing it might be something like:
```
file_idx = offset / (maximum size of block file)
offset = offset % (maximum size of block file)
```
Thanks!

**Comment by SwordYork** [comment]
Hello,

`start_pos = pos + 16 + 51` is a nice approach.

After inspecting the `avatar.index` and `avatar.block.0000x` in my friends' wechat, I guess the `file_idx` is calculated by `file_idx = pos >> 32`, and `file_idx` may be large than 9,  then the block of avatar  could be
```python
file_idx = pos >> 32 
fname = os.path.join(self.avt_dir, 'avatar.block.' + '{:05d}'.format(file_idx)) 
```

ps. I think that reinstall wechat will generate multiple avatar blocks. We need more examples to verify  `file_idx = offset >> 32`.

**Pull request merged**
