### PR TITLE
Add new params for decrypting the database

### PR DESCRIPTION
**Pull request by rom1504**
found necessary while investigating in #95

inspired by https://blog.greycode.top/posts/android-wechat-bak/

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Which version of sqlcipher are you using?

**Comment by rom1504** [comment]
I see, https://github.com/sqlcipher/sqlcipher/commit/e4b66d6cc8a2b7547a32ff2c3ac52f148eba3516 was meant to make these params non necessary

hmm indeed when I do it manually with sqlcipher binary it seems to work without these params now...

**Comment by rom1504** [comment]
ok I add to `sudo apt-get remove libsqlcipher0` so it would use the newer version of sqlcipher
so indeed we don't need this PR

**Comment by ppwwyyxx** [comment]
I wonder why the check https://github.com/ppwwyyxx/wechat-dump/blob/baef03db850de2708f095405c93b8d3913a6ebfd/decrypt-db.py#L140-L142 is not effective for you

**Comment by rom1504** [comment]
Yeah it's my bad, I had disabled it assuming that there was an error in the
check since I thought I had installed fully the right version already.

**Pull request closed without merging**
