### PR TITLE
Add some bsd compatibility & darwin version of sqlcipher

### PR DESCRIPTION
**Pull request by vuryleo**
RT

### CODE REVIEW

**Comment by vuryleo** [comment]
It's a dynamic linked version of `sqlcipher`. So it may not work on others' computer... Further step is needed somehow.

**Comment by vuryleo** [comment]
some useless file is removed, the repo is clean again.

**Comment by ppwwyyxx** [comment]
Seems elegant. I saw in android-interact and decrypt_db, that some 'grep' are not replaced by $GREP. Are you sure that they worked? I cannot verify it myself.

**Comment by vuryleo** [comment]
For that `grep` of bsd will perform `non-greedy` match with option `-o`, only the `grep`s with option `-o` need to be replaced with `egrep`, aka `grep -E`.

**Pull request merged**
